data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 2
    wrap: False
    train:
      target: datasets.ruijin.Ruijin_3D_Mask
      params:
        split: train
        max_size: null
    validation:
      target: datasets.ruijin.Ruijin_3D_Mask
      params:
        split: val
        max_size: 10
    test:
      target: datasets.ruijin.Ruijin_3D_Mask
      params:
        split: test
        max_size: 8

model:
  base_learning_rate: 4.5e-6
  target: train.trainer.CCDM
  params:
    use_scheduler: false
    scheduler_config:
      target: train.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [10000]
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [1.]
    monitor: "val/rec_loss"
    diffusion_model_config:
      target: train.ccdm.DiffusionModel
      params:
        schedule: cosine
        num_classes: 12
    denoising_model_config:
      target: train.ccdm.DenoisingModel
      params:
        unet_config:
          target: ddpm.models.unet_openai.unet.UNetModel
          params:
            in_channels: 12
            out_channels: 12
            model_channels: 64
            num_res_blocks: 2
            cond_encoded_shape: null
            num_heads: 1
            num_head_channels: 32
            channel_mult: [1, 2, 2, 4, 8]
            attention_resolutions: [32, 16, 8]
            use_checkpoint: true
            dims: 3
            use_spatial_transformer: true
            transformer_depth: 1
            context_dim: 5120
            ce_head: false
        step_T_sample: majority
    loss_config:
      lpips: 
        target: train.eval_metrics.pretrained_lpips
      ce_loss:
        target: torch.nn.CrossEntropyLoss
      # kl_div:
      #   target: train.loss.DiffusionKLLoss
      l1_loss:
        coeff: 1000

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        train_batch_frequency: 400
        val_batch_frequency: 1
        max_images: 20
        log_images_kwargs:
          ddim_steps: null
        log_first_step: false
  trainer:
    max_epochs: 1000
    num_sanity_val_steps: 0
